site_name: LibreTime
theme: readthedocs

dev_addr: '0.0.0.0:8888'
site_dir: 'build/docs'
docs_dir: 'docs'
markdown_extensions:
- codehilite:
    noclasses: True
    pygments_style: emacs

repo_url: https://github.com/LibreTime/libretime/

extra_css:
  - '_css/term.css'

pages:
  - 'Home': index.md
  - 'What is LibreTime?': manual/index.md
  - 'Features': features.md
  - 'F.A.Q.': faq.md
  - 'Rights and Royalties': manual/rights-and-royalties/index.md
  - 'Using LibreTime':
    - 'On Air in 60 seconds!': 'manual/on-air-in-60-seconds/index.md'
    - 'Getting Started': manual/getting-started/index.md
    - 'Tutorials': manual/tutorials/index.md
    - 'How-Tos': manual/howtos/index.md
  - 'The Main Menus':
    - 'Upload': manual/upload/index.md
    - 'Dashboard': manual/dashboard/index.md
    - 'Tracks': manual/tracks/index.md
    - 'Playlists': manual/playlists/index.md
    - 'Smart Blocks': manual/smartblocks/index.md
    - 'Webstreams': manual/webstreams/index.md
    - 'Podcasts': manual/podcasts/index.md
    - 'My Podcast': manual/my-podcast/index.md
    - 'Radio Page': manual/radio-page/index.md
    - 'Calendar': manual/calendar/index.md
    - 'Widgets': manual/widgets/index.md
    - 'Settings':
      - 'General': manual/general/index.md
      - 'Users': manual/users/index.md
      - 'Streams': manual/stream-settings/index.md
      - 'Status': manual/status/index.md
    - 'Analytics': manual/listener-stats/index.md
    - 'Help': manual/help/index.md
    - 'Listen': manual/listen/index.md
  - 'The Analytics Menu':
    - 'Playout History' : manual/history/index.md
    - 'History Templates' : manual/history-templates/index.md
    - 'Listener Stats' : manual/listener-stats/index.md
  - 'LibreTime in the Studio':
    - 'Preparing Media for Ingest': manual/preparing-media-for-ingest/index.md
    - 'Live Shows with Mixxx': manual/live-shows-with-mixxx/index.md
    - 'Smartphone Journalism': manual/smartphone-journalism/index.md
    - 'Icecast and SHOUTcast': manual/icecast-and-shoutcast/index.md
    - 'Recording Shows': manual/recording-shows/index.md
  - 'Installation':
    - 'Install': install.md
    - 'Preparing the Server': manual/preparing-the-server/index.md
    - 'Setting the Server Time': manual/setting-the-server-time/index.md
  - 'Administration':
    - 'Backing Up the Server': manual/backing-up-the-server/index.md
    - 'Media Folders': manual/media-folders/index.md
    - 'Upgrading': manual/upgrading/index.md
    - 'Troubleshooting': manual/troubleshooting/index.md
  - 'Advanced Configuration':
    - 'Icecast Handover': manual/icecast-handover/index.md
    - 'Promoting Your Station': manual/promoting-your-station/index.md
    - 'Stream Player for Your Website': manual/stream-player-for-your-website/index.md
    - 'Exporting the Schedule': manual/exporting-the-schedule/index.md
    - 'Interface Customization': manual/interface-customization/index.md
    - 'Interface Localization': manual/interface-localization/index.md
    - 'Host Configuration': manual/host-configuration/index.md
    - 'LibreTime API Authentication': manual/airtime-api-authentication/index.md
    - 'Secure Login with SSL or TLS': manual/secure-login-with-ssl/index.md
    - 'Icecast Statistics with Piwik': manual/icecast-statistics-with-piwik/index.md
    - 'FreeIPA Authentication': freeipa.md
  - 'Development':
    - 'Testing': testing.md
    - 'Database': database.md
    - 'Vagrant': vagrant.md
    - 'Translating': translating.md
    - 'Documentation': documentation.md
  - 'Appendix':
    - 'HD Audio Models': manual/hd-audio-models/index.md
    - 'About This Manual': manual/about-this-manual/index.md
