name: Website Preview

on:
  pull_request_target:
    branches: [main]
    types: [opened, synchronize, closed, reopened]
    paths:
      - .github/workflows/website-preview.yml
      - website/**
      - docs/**

env:
  # PREVIEW_DEPLOY_KEY is present in the secrets
  PREVIEW_EXTERNAL_REPOSITORY: libretime/libretime.github.io
  PREVIEW_URL: https://libretime.github.io
  PREVIEW_BASE_URL: /

jobs:
  deploy:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    name: Deploy
    runs-on: ubuntu-latest

    environment: website-preview

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - name: Find preview link comment
        uses: peter-evans/find-comment@v2
        id: found-link-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: Preview deployment

      - name: Update preview link comment
        uses: peter-evans/create-or-update-comment@v1.4.5
        id: link-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.found-link-comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            ### Preview deployment ${{ github.sha }}

            âŒ› Build in progress

            ${{ env.PREVIEW_URL }}${{ env.PREVIEW_BASE_URL }}pr-${{ github.event.pull_request.number }}/

      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn
          cache-dependency-path: ./website/yarn.lock

      - name: Install
        working-directory: website
        run: yarn install --frozen-lockfile

      - name: Build
        working-directory: website
        run: yarn build
        env:
          URL: ${{ env.PREVIEW_URL }}
          BASE_URL: ${{ env.PREVIEW_BASE_URL }}pr-${{ github.event.pull_request.number }}/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: ${{ env.PREVIEW_EXTERNAL_REPOSITORY }}
          deploy_key: ${{ secrets.PREVIEW_DEPLOY_KEY }}
          publish_dir: website/build
          destination_dir: pr-${{ github.event.pull_request.number }}
          keep_files: true

      - name: Update preview link comment
        uses: peter-evans/create-or-update-comment@v1.4.5
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.link-comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            ### Preview deployment ${{ github.sha }}

            ðŸ˜Ž Deployment is ready!

            ${{ env.PREVIEW_URL }}${{ env.PREVIEW_BASE_URL }}pr-${{ github.event.pull_request.number }}/

  clean:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    name: Clean
    runs-on: ubuntu-latest

    environment: website-preview

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ env.PREVIEW_EXTERNAL_REPOSITORY }}
          ssh-key: ${{ secrets.PREVIEW_DEPLOY_KEY }}

      - name: Clean files
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

          rm -fR pr-${{ github.event.pull_request.number }}

          git add .
          git commit -m "Clean pr-${{ github.event.pull_request.number }} preview"
          git push
